### ISSUE TITLE
Headless tests fail on Travis but tests pass on Appveyor and Intellij

### ISSUE THREAD

**Issue by zioul123** [nus-cs2103-AY1819S1/forum#113]
My group ran into an error where our tests pass on Intellij and Appveyor, but will fail when gradlew headless tests are run. They also fail on Travis.
Here is the stacktrace of our failed tests:
```
systemtests.EditCommandSystemTest > edit FAILED
    java.lang.IllegalStateException
        at java.base/java.util.Optional.orElseThrow(Optional.java:385)
        at guitests.guihandles.PersonListPanelHandle.getPersonCardHandle(PersonListPanelHandle.java:109)
        at seedu.address.ui.testutil.GuiTestAssert.assertListMatching(GuiTestAssert.java:95)
        at seedu.address.ui.testutil.GuiTestAssert.assertListMatching(GuiTestAssert.java:104)
        at systemtests.AddressBookSystemTest.assertApplicationDisplaysExpected(AddressBookSystemTest.java:184)
        at systemtests.EditCommandSystemTest.assertCommandSuccess(EditCommandSystemTest.java:476)
        at systemtests.EditCommandSystemTest.assertCommandSuccess(EditCommandSystemTest.java:446)
        at systemtests.EditCommandSystemTest.assertCommandSuccess(EditCommandSystemTest.java:429)
        at systemtests.EditCommandSystemTest.edit(EditCommandSystemTest.java:130)
```

I just wanted to check if anyone else has run into such problems where the tests pass in non-headless mode but fail on headless mode. 

The tests started failing on the PR here: https://github.com/CS2103-AY1819S1-W13-1/main/pull/71/files , where my untrained eye cannot see any reason why the test should start throwing an invalid state exception. My suspicion was that it was due to changes in the length of the typical persons address book, causing the UI to glitch, but no real known reason.

**Comment by zioul123** [comment]
The error can be "removed" by removing every person after Jenny in typicalPersonsAddressBook.xml and removing every name after Jenny in TypicalPersons.java. Other than list length as a possible reason for the failing test, we are completely stumped.

**Comment by damithc** [comment]
Just a general tip: start a new branch, add this code in smaller increments, and run test after each addition. The idea is to narrow down the scope of the problem. e.g., if you think it is something to do with the list length, try increasing the list length without changing anything else.
